### PR TITLE
Add an anonymity/privacy section

### PR DESCRIPTION
**Pull request by kevinwin**
Thoughts on adding a section on anonymity and privacy in step 1?

### CODE REVIEW

**Comment by bucko13** [comment]
Hmmmm 🤔 I almost feel like Anonymity/Privacy could have it's own dedicated page or section. Might be good to have just a brief overview in step1 and then a separate privacy.md that talks about/links to the broader ideas around the topic, different approaches by different chains, etc.

**Comment by kevinwin** [comment]
Sounds reasonable. I'll create some basic scaffolding later today.

**Comment by bucko13** [comment]
Looks good! The only other thing I think would be useful would be a section like "Current Approaches"? Then can link/outline CT, Ring Signatures, Mimblewimble, ZK-Snarks, ZK-Starks, Bulletproofs, and all of their related chains (Zcash, Monero, Grin)

**Comment by kevinwin** [comment]
Good idea. What I'll do is create those sections and whenever those sections are filled in, the specific related chain can be mentioned.

**Review by bucko13 — APPROVED** [review]

**Comment by bucko13** [comment]
Awesome!

**Pull request merged**
